// Package main demonstrates reaction format conversion examples
// coding=utf-8
// @Project : go-indigo
// @Time    : 2025/11/08
// @Author  : chengxiang.luo
// @Email   : chengxiang.luo@foxmail.com
// @File    : reaction_formats.go
// @Software: GoLand
package main

import (
	"fmt"
	"github.com/cx-luo/go-indigo/core"
	"log"
	"os"
)

func main() {
	indigoInit, err := core.IndigoInit()
	if err != nil {
		panic(err)
	}

	// Create a reaction from SMILES
	// Example: Fischer esterification (acetic acid + ethanol -> ethyl acetate + water)
	rxnSmiles := `<?xml version="1.0" encoding="UTF-8"?><cml xmlns="http://www.chemaxon.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.chemaxon.com/marvin/schema/mrvSchema_16_02_15.xsd" version="ChemAxon file format v16.02.15, generated by v16.10.10.0">
<MHead><MarvinGUI><mprop name="saveproperties" dataType="xsd:boolean" value="true"></mprop><mprop name="aminoAcidBondColoringEnabled" dataType="xsd:boolean" value="true"></mprop><mprop name="automaticReactionEnabled" dataType="xsd:boolean" value="true"></mprop><mprop name="setColoringEnabled" dataType="xsd:boolean" value="true"></mprop><mprop name="atomNumberingType" dataType="xsd:integer" value="0"></mprop><mprop name="fogFactor" dataType="xsd:integer" value="66"></mprop><mprop name="automaticFogEnabled" dataType="xsd:boolean" value="false"></mprop><mprop name="atomPropertiesVisible" dataType="xsd:boolean" value="true"></mprop><mprop name="atomMappingVisible" dataType="xsd:boolean" value="true"></mprop><mprop name="EZVisible" dataType="xsd:boolean" value="false"></mprop><mprop name="mpVisible" dataType="xsd:boolean" value="false"></mprop><mprop name="bondLength" dataType="xsd:double" value="28.0"></mprop><mprop name="bondLengthVisible" dataType="xsd:boolean" value="false"></mprop><mprop name="valenceErrorVisible" dataType="xsd:boolean" value="true"></mprop><mprop name="valenceErrorVisibleInView" dataType="xsd:boolean" value="false"></mprop><mprop name="atomSymbolVisible3D" dataType="xsd:boolean" value="true"></mprop><mprop name="rgroupsVisible" dataType="xsd:boolean" value="true"></mprop><mprop name="lonePairsAutoCalc" dataType="xsd:boolean" value="true"></mprop><mprop name="lonePairsAsLine" dataType="xsd:boolean" value="false"></mprop><mprop name="chargeWithCircle" dataType="xsd:boolean" value="false"></mprop><mprop name="molbg" value="#ffffff"></mprop><mprop name="chiralitySupport" dataType="xsd:integer" value="3"></mprop><mprop name="atomsize" dataType="xsd:double" value="0.35714285714"></mprop><mprop name="boldBondWidth" dataType="xsd:double" value="5.0"></mprop><mprop name="bondSpacing" dataType="xsd:double" value="0.180375"></mprop><mprop name="bondHashSpacing" dataType="xsd:double" value="0.15"></mprop><mprop name="wireThickness" dataType="xsd:double" value="0.066666"></mprop><mprop name="stickThickness" dataType="xsd:double" value="0.1"></mprop><mprop name="ballRadius" dataType="xsd:double" value="0.5"></mprop><mprop name="rendering" value="wireframe"></mprop><mprop name="downWedge" value="mdl"></mprop><mprop name="coordinateBondStyle" value="arrow"></mprop><mprop name="coordinateBondStyleAtMulticenter" value="hashed"></mprop><mprop name="anybond" value="auto"></mprop><mprop name="sketchAnyBond" value="auto"></mprop><mprop name="viewAnyBond" value="auto"></mprop><mprop name="atomFont" dataType="xsd:mfont" value="SansSerif-PLAIN-10"></mprop><mprop name="sketchImplicitH" value="heteroterm"></mprop><mprop name="lonePairsVisible" dataType="xsd:boolean" value="false"></mprop><mprop name="autoscale" dataType="xsd:boolean" value="false"></mprop><mprop name="absLabelVisible" dataType="xsd:boolean" value="false"></mprop><mprop name="colorScheme" value="cpk"></mprop><mprop name="viewCarbonVisibility" value="inChain"></mprop><mprop name="sketchCarbonVisibility" value="inChain"></mprop><mprop name="viewLigandOrderVisibility" value="showOnlyWithDefinition"></mprop><mprop name="sketchLigandOrderVisibility" value="showOnlyWithDefinition"></mprop><mprop name="rLogicVisible" value="off"></mprop><mprop name="peptideDisplayType" value="3-letter"></mprop><mprop name="zeroBasedAtomIndexing" dataType="xsd:boolean" value="false"></mprop><mprop name="valencePropertyVisible" dataType="xsd:boolean" value="true"></mprop><mprop name="ligandErrorVisible" dataType="xsd:boolean" value="true"></mprop><mprop name="sketchArrowHeadLength" dataType="xsd:double" value="0.8"></mprop><mprop name="sketchArrowHeadWidth" dataType="xsd:double" value="0.5"></mprop><mprop name="sketchArrowTailLength" dataType="xsd:double" value="0.8"></mprop><mprop name="sketchArrowTailWidth" dataType="xsd:double" value="0.5"></mprop></MarvinGUI></MHead>
<MDocument><MChemicalStruct><reaction><arrow type="DEFAULT" x1="-0.7552914184268165" y1="-0.016872869814404723" x2="3.487142511956174" y2="-0.016872869814404723"></arrow><reactantList><molecule molID="m1"><atomArray atomID="a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18 a19 a20" elementType="C O C C C C C C C C O C C C C O C C O C" x2="-17.228395609140165 -17.22839560914017 -15.894716487312133 -15.894716487312134 -14.561037365484097 -14.5610373654841 -15.894716487312138 -17.228395609140172 -17.228395609140172 -18.562074730968202 -19.89575385279624 -21.229432974624274 -18.5620747309682 -17.228395609140165 -17.22839560914016 -18.562074730968195 -15.89471648731213 -15.894716487312131 -14.561037365484095 -14.561037365484097" y2="1.1709528351268794 -0.3690471648731215 -1.1390471648731224 -2.6790471648731224 -3.4490471648731265 -4.989047164873127 -5.759047164873125 -4.9890471648731225 -3.4490471648731225 1.9409528351268843 1.1709528351268865 1.9409528351268897 3.4809528351268835 4.250952835126881 5.79095283512688 6.560952835126882 3.48095283512688 1.940952835126879 1.1709528351268776 -0.3690471648731215"></atomArray><bondArray><bond id="b1" atomRefs2="a1 a2" order="1"></bond><bond id="b2" atomRefs2="a2 a3" order="1"></bond><bond id="b3" atomRefs2="a3 a4" order="1"></bond><bond id="b4" atomRefs2="a4 a5" order="1"></bond><bond id="b5" atomRefs2="a5 a6" order="2"></bond><bond id="b6" atomRefs2="a6 a7" order="1"></bond><bond id="b7" atomRefs2="a7 a8" order="2"></bond><bond id="b8" atomRefs2="a8 a9" order="1"></bond><bond id="b9" atomRefs2="a4 a9" order="2"></bond><bond id="b10" atomRefs2="a1 a10" order="1"></bond><bond id="b11" atomRefs2="a10 a11" order="1"></bond><bond id="b12" atomRefs2="a11 a12" order="1"></bond><bond id="b13" atomRefs2="a10 a13" order="2"></bond><bond id="b14" atomRefs2="a13 a14" order="1"></bond><bond id="b15" atomRefs2="a14 a15" order="1"></bond><bond id="b16" atomRefs2="a15 a16" order="2"></bond><bond id="b17" atomRefs2="a14 a17" order="2"></bond><bond id="b18" atomRefs2="a17 a18" order="1"></bond><bond id="b19" atomRefs2="a1 a18" order="2"></bond><bond id="b20" atomRefs2="a18 a19" order="1"></bond><bond id="b21" atomRefs2="a19 a20" order="1"></bond></bondArray></molecule><molecule molID="m2"><atomArray atomID="a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18 a19 a20 a21 a22 a23 a24 a25" elementType="P O O C C O C C C C C C C O C C C C C C C C O C C" x2="-7.081037365484097 -6.311037365484095 -8.41471648731213 -8.414716487312129 -9.748395609140164 -7.851037365484096 -9.391037365484097 -10.161037365484095 -5.747358243656061 -5.747358243656064 -4.413679121828025 -4.413679121828029 -5.747358243656066 -5.747358243656068 -4.413679121828036 -4.413679121828038 -3.08 -3.0800000000000036 -4.413679121828041 -5.747358243656075 -5.747358243656073 -7.0810373654841 -8.414716487312136 -9.748395609140172 -7.0810373654841" y2="4.620000000000002 5.953679121828038 5.390000000000003 6.930000000000002 7.700000000000004 3.286320878171968 3.2863208781719697 4.620000000000007 3.8500000000000023 2.3100000000000023 1.5399999999999991 -8.881784197001252E-16 -0.7699999999999996 -2.3099999999999996 -3.0800000000000027 -4.620000000000002 -5.390000000000007 -6.930000000000006 -7.700000000000004 -6.930000000000002 -5.3900000000000015 2.6645352591003757E-15 -0.7699999999999969 4.440892098500626E-15 1.5400000000000027"></atomArray><bondArray><bond id="b1" atomRefs2="a1 a2" order="2"></bond><bond id="b2" atomRefs2="a1 a3" order="1"></bond><bond id="b3" atomRefs2="a3 a4" order="1"></bond><bond id="b4" atomRefs2="a4 a5" order="1"></bond><bond id="b5" atomRefs2="a1 a6" order="1"></bond><bond id="b6" atomRefs2="a6 a7" order="1"></bond><bond id="b7" atomRefs2="a7 a8" order="1"></bond><bond id="b8" atomRefs2="a1 a9" order="1"></bond><bond id="b9" atomRefs2="a9 a10" order="1"></bond><bond id="b10" atomRefs2="a10 a11" order="1"></bond><bond id="b11" atomRefs2="a11 a12" order="2"></bond><bond id="b12" atomRefs2="a12 a13" order="1"></bond><bond id="b13" atomRefs2="a13 a14" order="1"></bond><bond id="b14" atomRefs2="a14 a15" order="1"></bond><bond id="b15" atomRefs2="a15 a16" order="1"></bond><bond id="b16" atomRefs2="a16 a17" order="2"></bond><bond id="b17" atomRefs2="a17 a18" order="1"></bond><bond id="b18" atomRefs2="a18 a19" order="2"></bond><bond id="b19" atomRefs2="a19 a20" order="1"></bond><bond id="b20" atomRefs2="a20 a21" order="2"></bond><bond id="b21" atomRefs2="a16 a21" order="1"></bond><bond id="b22" atomRefs2="a13 a22" order="2"></bond><bond id="b23" atomRefs2="a22 a23" order="1"></bond><bond id="b24" atomRefs2="a23 a24" order="1"></bond><bond id="b25" atomRefs2="a22 a25" order="1"></bond><bond id="b26" atomRefs2="a10 a25" order="2"></bond></bondArray></molecule></reactantList><productList><molecule molID="m3"><atomArray atomID="a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18 a19 a20 a21 a22 a23 a24 a25 a26 a27 a28 a29 a30 a31 a32 a33 a34 a35 a36 a37" elementType="C O C C C C C C C C O C C C C C C C C C O C C C C C C C C O C C C C O C O" x2="9.941037365484108 9.941037365484105 11.27471648731214 11.274716487312137 12.608395609140176 12.608395609140173 11.274716487312137 9.941037365484101 9.941037365484103 8.607358243656071 7.2736791218280334 5.940000000000001 8.607358243656076 9.941037365484114 9.941037365484117 8.607358243656085 8.60735824365609 7.273679121828054 7.27367912182806 8.607358243656098 8.607358243656105 7.273679121828071 7.273679121828077 5.94000000000004 5.9400000000000475 7.273679121828086 8.607358243656119 8.607358243656114 9.94103736548413 11.274716487312167 12.608395609140201 9.941037365484128 11.274716487312148 11.274716487312144 12.60839560914018 12.608395609140176 17.0083956091402" y2="-5.00500000000001 -6.545000000000009 -7.315000000000008 -8.855000000000008 -9.62500000000001 -11.16500000000001 -11.935000000000006 -11.16500000000001 -9.625000000000007 -4.235000000000003 -5.004999999999999 -4.234999999999994 -2.6950000000000034 -1.9250000000000076 -0.38500000000000667 0.38499999999999823 1.9249999999999967 2.6950000000000034 4.235000000000003 5.004999999999998 6.544999999999999 7.315000000000003 8.855000000000004 9.62500000000001 11.16500000000001 11.935000000000006 11.165000000000001 9.625 4.234999999999994 5.004999999999991 4.234999999999987 2.6949999999999945 -2.6950000000000105 -4.23500000000001 -5.005000000000011 -6.545000000000012 -0.32083333333333974"></atomArray><bondArray><bond id="b1" atomRefs2="a1 a2" order="1"></bond><bond id="b2" atomRefs2="a1 a10" order="2"></bond><bond id="b3" atomRefs2="a1 a34" order="1"></bond><bond id="b4" atomRefs2="a2 a3" order="1"></bond><bond id="b5" atomRefs2="a3 a4" order="1"></bond><bond id="b6" atomRefs2="a4 a5" order="1"></bond><bond id="b7" atomRefs2="a4 a9" order="2"></bond><bond id="b8" atomRefs2="a5 a6" order="2"></bond><bond id="b9" atomRefs2="a6 a7" order="1"></bond><bond id="b10" atomRefs2="a7 a8" order="2"></bond><bond id="b11" atomRefs2="a8 a9" order="1"></bond><bond id="b12" atomRefs2="a10 a11" order="1"></bond><bond id="b13" atomRefs2="a10 a13" order="1"></bond><bond id="b14" atomRefs2="a11 a12" order="1"></bond><bond id="b15" atomRefs2="a13 a14" order="2"></bond><bond id="b16" atomRefs2="a14 a15" order="1"></bond><bond id="b17" atomRefs2="a14 a33" order="1"></bond><bond id="b18" atomRefs2="a15 a16" order="2"></bond><bond id="b19" atomRefs2="a16 a17" order="1"></bond><bond id="b20" atomRefs2="a17 a18" order="1"></bond><bond id="b21" atomRefs2="a17 a32" order="2"></bond><bond id="b22" atomRefs2="a18 a19" order="2"></bond><bond id="b23" atomRefs2="a19 a20" order="1"></bond><bond id="b24" atomRefs2="a20 a21" order="1"></bond><bond id="b25" atomRefs2="a20 a29" order="2"></bond><bond id="b26" atomRefs2="a21 a22" order="1"></bond><bond id="b27" atomRefs2="a22 a23" order="1"></bond><bond id="b28" atomRefs2="a23 a24" order="1"></bond><bond id="b29" atomRefs2="a23 a28" order="2"></bond><bond id="b30" atomRefs2="a24 a25" order="2"></bond><bond id="b31" atomRefs2="a25 a26" order="1"></bond><bond id="b32" atomRefs2="a26 a27" order="2"></bond><bond id="b33" atomRefs2="a27 a28" order="1"></bond><bond id="b34" atomRefs2="a29 a30" order="1"></bond><bond id="b35" atomRefs2="a29 a32" order="1"></bond><bond id="b36" atomRefs2="a30 a31" order="1"></bond><bond id="b37" atomRefs2="a33 a34" order="2"></bond><bond id="b38" atomRefs2="a34 a35" order="1"></bond><bond id="b39" atomRefs2="a35 a36" order="1"></bond></bondArray></molecule></productList></reaction></MChemicalStruct><MReactionSign id="o2" fontScale="18.0" halign="CENTER" valign="CENTER" autoSize="true"><Field name="text"><![CDATA[{D font=SansSerif,size=18,bold}+]]></Field><MPoint x="-12.512287365484099" y="0.9179528351269859"></MPoint><MPoint x="-11.907287365484102" y="0.9179528351269859"></MPoint><MPoint x="-11.907287365484102" y="-0.3470471648730147"></MPoint><MPoint x="-12.512287365484099" y="-0.3470471648730147"></MPoint></MReactionSign></MDocument>
</cml>
`

	rxn, err := indigoInit.LoadReactionFromString(rxnSmiles)
	if err != nil {
		log.Fatalf("Failed to load reaction: %v", err)
	}
	defer rxn.Close()

	fmt.Println("=== Reaction Format Conversion Examples ===\n")

	// 2. Canonical SMILES
	if result, err := rxn.ToCanonicalSmiles(); err == nil {
		fmt.Printf("Canonical SMILES: %s\n", result)
	} else {
		fmt.Printf("Canonical SMILES Error: %v\n", err)
	}

	// 3. ChemAxon Extended SMILES (CXSmiles)
	fmt.Println("\n--- ChemAxon CXSmiles ---")
	if result, err := rxn.ToCXSmiles(); err == nil {
		fmt.Printf("CXSmiles: %s\n", result)
	} else {
		fmt.Printf("CXSmiles Error: %v\n", err)
	}

	// 4. Canonical ChemAxon Extended SMILES
	if result, err := rxn.ToCanonicalSmiles(); err == nil {
		fmt.Printf("Canonical CXSmiles: %s\n", result)
	} else {
		fmt.Printf("Canonical CXSmiles Error: %v\n", err)
	}

	// 5. Daylight SMILES
	if result, err := rxn.ToDaylightSmiles(); err == nil {
		fmt.Printf("Daylight SMILES: %s\n", result)
	} else {
		fmt.Printf("Daylight SMILES Error: %v\n", err)
	}

	// 6. SMARTS
	fmt.Println("\n--- SMARTS Format ---")
	if result, err := rxn.ToSmarts(); err == nil {
		fmt.Printf("SMARTS: %s\n", result)
	} else {
		fmt.Printf("SMARTS Error: %v\n", err)
	}

	// 7. Canonical SMARTS
	if result, err := rxn.ToCanonicalSmarts(); err == nil {
		fmt.Printf("Canonical SMARTS: %s\n", result)
	} else {
		fmt.Printf("Canonical SMARTS Error: %v\n", err)
	}

	// 8. RXN file format
	fmt.Println("\n--- RXN File Format ---")
	if result, err := rxn.ToRxnfile(); err == nil {
		fmt.Printf("RXN file (first 300 chars): %s...\n", truncate(result, 300))
	} else {
		fmt.Printf("RXN file Error: %v\n", err)
	}

	// 9. CML (Chemical Markup Language)
	fmt.Println("\n--- CML Format ---")
	if result, err := rxn.ToCML(); err == nil {
		fmt.Printf("CML (first 300 chars): %s...\n", truncate(result, 300))
	} else {
		fmt.Printf("CML Error: %v\n", err)
	}

	// 10. CDXML
	fmt.Println("\n--- CDXML Format ---")
	if result, err := rxn.ToCDXML(); err == nil {
		fmt.Printf("CDXML (first 200 chars): %s...\n", truncate(result, 200))
	} else {
		fmt.Printf("CDXML Error: %v\n", err)
	}

	// 11. CDX Base64
	fmt.Println("\n--- CDX Base64 Format ---")
	if result, err := rxn.ToCDXBase64(); err == nil {
		fmt.Printf("CDX Base64 (first 100 chars): %s...\n", truncate(result, 100))
	} else {
		fmt.Printf("CDX Base64 Error: %v\n", err)
	}

	// 12. JSON/KET (Ketcher format)
	fmt.Println("\n--- JSON/KET Format ---")
	if result, err := rxn.ToJSON(); err == nil {
		fmt.Printf("JSON (first 200 chars): %s...\n", truncate(result, 200))
	} else {
		fmt.Printf("JSON Error: %v\n", err)
	}

	// 12a. KET format (alias for JSON)
	if result, err := rxn.ToKet(); err == nil {
		fmt.Printf("KET (first 200 chars): %s...\n", truncate(result, 200))
	} else {
		fmt.Printf("KET Error: %v\n", err)
	}

	// 14. RDF Format
	fmt.Println("\n--- RDF Format ---")
	if result, err := rxn.ToRDF(); err == nil {
		fmt.Printf("RDF (first 300 chars): %s...\n", truncate(result, 300))
	} else {
		fmt.Printf("RDF Error: %v\n", err)
	}

	// 15. Save to various file formats
	fmt.Println("\n--- Saving to Files ---")

	// Save as RXN file
	if err := rxn.SaveToFile("fischer_esterification.rxn"); err == nil {
		fmt.Println("✓ Saved to fischer_esterification.rxn")
		defer os.Remove("fischer_esterification.rxn")
	} else {
		fmt.Printf("✗ Failed to save RXN file: %v\n", err)
	}

	// Save as JSON file
	if err := rxn.SaveToJSONFile("fischer_esterification.json"); err == nil {
		fmt.Println("✓ Saved to fischer_esterification.json")
		defer os.Remove("fischer_esterification.json")
	} else {
		fmt.Printf("✗ Failed to save JSON file: %v\n", err)
	}

	// Save as KET file (Ketcher format)
	if err := rxn.SaveToKetFile("fischer_esterification.ket"); err == nil {
		fmt.Println("✓ Saved to fischer_esterification.ket")
		defer os.Remove("fischer_esterification.ket")
	} else {
		fmt.Printf("✗ Failed to save KET file: %v\n", err)
	}

	// Save as CML file
	if err := rxn.SaveToCMLFile("fischer_esterification.cml"); err == nil {
		fmt.Println("✓ Saved to fischer_esterification.cml")
		defer os.Remove("fischer_esterification.cml")
	} else {
		fmt.Printf("✗ Failed to save CML file: %v\n", err)
	}

	// Save as CDXML file
	if err := rxn.SaveToCDXMLFile("fischer_esterification.cdxml"); err == nil {
		fmt.Println("✓ Saved to fischer_esterification.cdxml")
		defer os.Remove("fischer_esterification.cdxml")
	} else {
		fmt.Printf("✗ Failed to save CDXML file: %v\n", err)
	}

	// Save as CDX file
	if err := rxn.SaveToCDXFile("fischer_esterification.cdx"); err == nil {
		fmt.Println("✓ Saved to fischer_esterification.cdx")
		defer os.Remove("fischer_esterification.cdx")
	} else {
		fmt.Printf("✗ Failed to save CDX file: %v\n", err)
	}

	// Save as RDF file
	if err := rxn.SaveToRDFFile("fischer_esterification.rdf"); err == nil {
		fmt.Println("✓ Saved to fischer_esterification.rdf")
		defer os.Remove("fischer_esterification.rdf")
	} else {
		fmt.Printf("✗ Failed to save RDF file: %v\n", err)
	}

	// 16. Get reaction info
	fmt.Println("\n--- Reaction Information ---")
	reactants, _ := rxn.CountReactants()
	products, _ := rxn.CountProducts()
	catalysts, _ := rxn.CountCatalysts()
	fmt.Printf("Reactants: %d, Products: %d, Catalysts: %d\n", reactants, products, catalysts)

	fmt.Println("\n=== Format Conversion Complete ===")
}

// Helper function to truncate strings for display
func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen]
}
