// Example program demonstrating reaction package usage
// Build and run: go run example_reaction.go
package main

import (
	"fmt"
	"log"

	"github.com/cx-luo/go-chem/reaction"
)

func main() {
	fmt.Println("=== Reaction Package Example ===\n")

	// Example 1: Load a reaction from SMILES
	fmt.Println("1. Loading reaction from SMILES:")
	rxn := `<?xml version="1.0" encoding="windows-1252"?><cml xmlns="http://www.chemaxon.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.chemaxon.com/marvin/schema/mrvSchema_20_9_0.xsd" version="ChemAxon file format v20.9.0, generated by v20.8.0">
<MHead><MarvinGUI><mprop name="saveproperties" dataType="xsd:boolean" value="true"></mprop><mprop name="aminoAcidBondColoringEnabled" dataType="xsd:boolean" value="true"></mprop><mprop name="automaticReactionEnabled" dataType="xsd:boolean" value="true"></mprop><mprop name="setColoringEnabled" dataType="xsd:boolean" value="true"></mprop><mprop name="atomNumberingType" dataType="xsd:integer" value="0"></mprop><mprop name="fogFactor" dataType="xsd:integer" value="66"></mprop><mprop name="automaticFogEnabled" dataType="xsd:boolean" value="false"></mprop><mprop name="atomPropertiesVisible" dataType="xsd:boolean" value="true"></mprop><mprop name="atomMappingVisible" dataType="xsd:boolean" value="true"></mprop><mprop name="EZVisible" dataType="xsd:boolean" value="false"></mprop><mprop name="mpVisible" dataType="xsd:boolean" value="false"></mprop><mprop name="bondLength" dataType="xsd:double" value="28.0"></mprop><mprop name="bondLengthVisible" dataType="xsd:boolean" value="false"></mprop><mprop name="valenceErrorVisible" dataType="xsd:boolean" value="true"></mprop><mprop name="valenceErrorVisibleInView" dataType="xsd:boolean" value="false"></mprop><mprop name="atomSymbolVisible3D" dataType="xsd:boolean" value="true"></mprop><mprop name="rgroupsVisible" dataType="xsd:boolean" value="true"></mprop><mprop name="lonePairsAutoCalc" dataType="xsd:boolean" value="true"></mprop><mprop name="lonePairsAsLine" dataType="xsd:boolean" value="false"></mprop><mprop name="chargeWithCircle" dataType="xsd:boolean" value="false"></mprop><mprop name="molbg" value="#ffffff"></mprop><mprop name="chiralitySupport" dataType="xsd:integer" value="0"></mprop><mprop name="atomsize" dataType="xsd:double" value="0.35714285714"></mprop><mprop name="boldBondWidth" dataType="xsd:double" value="5.0"></mprop><mprop name="bondSpacing" dataType="xsd:double" value="0.180375"></mprop><mprop name="bondHashSpacing" dataType="xsd:double" value="0.15"></mprop><mprop name="wireThickness" dataType="xsd:double" value="0.066666"></mprop><mprop name="stickThickness" dataType="xsd:double" value="0.1"></mprop><mprop name="ballRadius" dataType="xsd:double" value="0.5"></mprop><mprop name="rendering" value="wireframe"></mprop><mprop name="downWedge" value="mdl"></mprop><mprop name="coordinateBondStyle" value="arrow"></mprop><mprop name="coordinateBondStyleAtMulticenter" value="hashed"></mprop><mprop name="anybond" value="auto"></mprop><mprop name="sketchAnyBond" value="auto"></mprop><mprop name="viewAnyBond" value="auto"></mprop><mprop name="atomFont" dataType="xsd:mfont" value="SansSerif-PLAIN-10"></mprop><mprop name="sketchImplicitH" value="heteroterm"></mprop><mprop name="lonePairsVisible" dataType="xsd:boolean" value="false"></mprop><mprop name="autoscale" dataType="xsd:boolean" value="false"></mprop><mprop name="absLabelVisible" dataType="xsd:boolean" value="false"></mprop><mprop name="colorScheme" value="cpk"></mprop><mprop name="viewCarbonVisibility" value="inChain"></mprop><mprop name="sketchCarbonVisibility" value="inChain"></mprop><mprop name="viewLigandOrderVisibility" value="showOnlyWithDefinition"></mprop><mprop name="sketchLigandOrderVisibility" value="showOnlyWithDefinition"></mprop><mprop name="rLogicVisible" value="off"></mprop><mprop name="peptideDisplayType" value="3-letter"></mprop><mprop name="zeroBasedAtomIndexing" dataType="xsd:boolean" value="false"></mprop><mprop name="valencePropertyVisible" dataType="xsd:boolean" value="true"></mprop><mprop name="ligandErrorVisible" dataType="xsd:boolean" value="true"></mprop><mprop name="sketchArrowHeadLength" dataType="xsd:double" value="0.8"></mprop><mprop name="sketchArrowHeadWidth" dataType="xsd:double" value="0.5"></mprop><mprop name="sketchArrowTailLength" dataType="xsd:double" value="0.8"></mprop><mprop name="sketchArrowTailWidth" dataType="xsd:double" value="0.5"></mprop><mprop name="scale" dataType="xsd:double" value="18.0"></mprop></MarvinGUI></MHead>
<MDocument><MChemicalStruct><reaction><arrow type="DEFAULT" x1="-1.0912356798648588" y1="0.23466859238039472" x2="2.8693469280475767" y2="0.23466859238039472"></arrow><reactantList><molecule molID="m1"><atomArray atomID="a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11" elementType="C O C C O N C C C N C" x2="-20.7621 -22.0958 -22.0958 -23.4294 -24.7631 -23.4294 -24.5184 -23.4294 -24.5184 -22.3405 -22.3405" y2="-3.9434 -3.1734 -1.6334 -0.8634 -1.6334 0.6766 1.7655 2.8545 3.9434 3.9434 1.7655"></atomArray><bondArray><bond id="b1" atomRefs2="a1 a2" order="1"></bond><bond id="b2" atomRefs2="a2 a3" order="1"></bond><bond id="b3" atomRefs2="a3 a4" order="1"></bond><bond id="b4" atomRefs2="a4 a5" order="2"></bond><bond id="b5" atomRefs2="a4 a6" order="1"></bond><bond id="b6" atomRefs2="a6 a7" order="1"></bond><bond id="b7" atomRefs2="a6 a11" order="1"></bond><bond id="b8" atomRefs2="a7 a8" order="1"></bond><bond id="b9" atomRefs2="a8 a9" order="1"></bond><bond id="b10" atomRefs2="a8 a10" order="1"></bond><bond id="b11" atomRefs2="a8 a11" order="1"></bond></bondArray></molecule><molecule molID="m2"><atomArray atomID="a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14" elementType="C O C C C C Cl C C N C O C N" x2="-3.0800 -4.4137 -4.4137 -3.0800 -3.0800 -4.4137 -4.4137 -5.7474 -5.7474 -7.0810 -8.4147 -8.4147 -9.7484 -11.0821" y2="3.6365 2.8665 1.3265 0.5565 -0.9835 -1.7535 -3.2935 -0.9835 0.5565 1.3265 0.5565 -0.9835 1.3265 0.5565"></atomArray><bondArray><bond id="b1" atomRefs2="a1 a2" order="1"></bond><bond id="b2" atomRefs2="a2 a3" order="1"></bond><bond id="b3" atomRefs2="a3 a4" order="2"></bond><bond id="b4" atomRefs2="a3 a9" order="1"></bond><bond id="b5" atomRefs2="a4 a5" order="1"></bond><bond id="b6" atomRefs2="a5 a6" order="2"></bond><bond id="b7" atomRefs2="a6 a7" order="1"></bond><bond id="b8" atomRefs2="a6 a8" order="1"></bond><bond id="b9" atomRefs2="a8 a9" order="2"></bond><bond id="b10" atomRefs2="a9 a10" order="1"></bond><bond id="b11" atomRefs2="a10 a11" order="1"></bond><bond id="b12" atomRefs2="a11 a12" order="2"></bond><bond id="b13" atomRefs2="a11 a13" order="1"></bond><bond id="b14" atomRefs2="a13 a14" order="1"></bond></bondArray></molecule></reactantList><productList><molecule molID="m3"><atomArray atomID="a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18 a19 a20 a21 a22 a23 a24 a25 a26 a27 a28 a29" elementType="O C O C F F F O C N C C C C O N C O C O C C C C C N C C C" lonePair="2 0 2 0 3 3 3 2 0 1 0 0 0 0 2 1 0 2 0 2 0 0 0 0 0 1 0 0 0" x2="5.0600 6.3937 7.7274 6.3937 6.3937 7.9337 4.8537 17.8230 18.2989 17.3937 15.8537 15.0837 13.5437 12.7737 11.2337 13.5437 15.0837 15.8537 18.2989 17.8230 19.7635 21.0972 22.4309 22.4309 23.8955 24.8007 23.8955 21.0972 19.7635" y2="-1.5288 -0.7588 -1.5288 0.7812 2.3212 0.7812 0.7812 -2.7105 -1.2459 -0.0000 -0.0000 -1.3337 -1.3337 -0.0000 -0.0000 1.3337 1.3337 2.6674 1.2459 2.7105 0.7700 1.5400 0.7700 -0.7700 -1.2459 -0.0000 1.2459 -1.5400 -0.7700"></atomArray><bondArray><bond id="b1" atomRefs2="a1 a2" order="1"></bond><bond id="b2" atomRefs2="a2 a3" order="2"></bond><bond id="b3" atomRefs2="a2 a4" order="1"></bond><bond id="b4" atomRefs2="a4 a5" order="1"></bond><bond id="b5" atomRefs2="a4 a6" order="1"></bond><bond id="b6" atomRefs2="a4 a7" order="1"></bond><bond id="b7" atomRefs2="a8 a9" order="2"></bond><bond id="b8" atomRefs2="a9 a10" order="1"></bond><bond id="b9" atomRefs2="a9 a29" order="1"></bond><bond id="b10" atomRefs2="a10 a11" order="1"></bond><bond id="b11" atomRefs2="a10 a19" order="1"></bond><bond id="b12" atomRefs2="a11 a12" order="1"></bond><bond id="b13" atomRefs2="a11 a17" order="1"></bond><bond id="b14" atomRefs2="a12 a13" order="1"></bond><bond id="b15" atomRefs2="a13 a14" order="1"></bond><bond id="b16" atomRefs2="a14 a15" order="2"></bond><bond id="b17" atomRefs2="a14 a16" order="1"></bond><bond id="b18" atomRefs2="a16 a17" order="1"></bond><bond id="b19" atomRefs2="a17 a18" order="2"></bond><bond id="b20" atomRefs2="a19 a20" order="2"></bond><bond id="b21" atomRefs2="a19 a21" order="1"></bond><bond id="b22" atomRefs2="a21 a22" order="2"></bond><bond id="b23" atomRefs2="a21 a29" order="1"></bond><bond id="b24" atomRefs2="a22 a23" order="1"></bond><bond id="b25" atomRefs2="a23 a24" order="2"></bond><bond id="b26" atomRefs2="a23 a27" order="1"></bond><bond id="b27" atomRefs2="a24 a25" order="1"></bond><bond id="b28" atomRefs2="a24 a28" order="1"></bond><bond id="b29" atomRefs2="a25 a26" order="1"></bond><bond id="b30" atomRefs2="a26 a27" order="1"></bond><bond id="b31" atomRefs2="a28 a29" order="2"></bond></bondArray></molecule></productList></reaction></MChemicalStruct><MReactionSign id="o2" fontScale="10.0" halign="CENTER" valign="CENTER" autoSize="false"><Field name="text"><![CDATA[{D font=SansSerif,size=18,bold}+]]></Field><MPoint x="-16.2221" y="0.9690"></MPoint><MPoint x="-15.6221" y="0.9690"></MPoint><MPoint x="-15.6221" y="-0.2960"></MPoint><MPoint x="-16.2221" y="-0.2960"></MPoint></MReactionSign></MDocument>
</cml>`
	fmt.Printf("   Input: %s\n", rxn)

	r, err := reaction.LoadReactionFromString(rxn)
	if err != nil {
		log.Fatalf("Failed to load reaction: %v", err)
	}
	defer r.Close()

	// Get counts
	reactantCount, _ := r.CountReactants()
	productCount, _ := r.CountProducts()
	catalystCount, _ := r.CountCatalysts()

	fmt.Printf("   Reactants: %d\n", reactantCount)
	fmt.Printf("   Products: %d\n", productCount)
	fmt.Printf("   Catalysts: %d\n\n", catalystCount)

	// Example 2: Convert to canonical SMILES
	fmt.Println("2. Converting to canonical SMILES:")
	canonicalSmiles, err := r.ToCanonicalSmiles()
	if err != nil {
		log.Fatalf("Failed to convert to canonical SMILES: %v", err)
	}
	fmt.Printf("   Canonical: %s\n\n", canonicalSmiles)

	// Example 3: Automatic atom mapping
	fmt.Println("3. Performing automatic atom mapping:")
	err = r.Automap(reaction.AutomapModeDiscard)
	if err != nil {
		log.Fatalf("Failed to automap: %v", err)
	}
	fmt.Println("   Mapping completed successfully\n")

	// Example 4: Convert to RXN format
	fmt.Println("4. Converting to RXN format:")
	rxnString, err := r.ToRxnfile()
	if err != nil {
		log.Fatalf("Failed to convert to RXN: %v", err)
	}
	fmt.Printf("   RXN length: %d bytes\n", len(rxnString))
	fmt.Println("   First line:", rxnString[:50], "...\n")

	// Example 5: Iterate over reactants
	fmt.Println("5. Iterating over reactants:")
	reactIter, err := r.IterateReactants()
	if err != nil {
		log.Fatalf("Failed to create iterator: %v", err)
	}
	defer reactIter.Close()

	idx := 0
	for reactIter.HasNext() {
		molHandle, err := reactIter.Next()
		if err != nil {
			log.Printf("Failed to get next molecule: %v", err)
			continue
		}
		fmt.Printf("   Reactant %d: handle=%d\n", idx, molHandle)
		idx++
	}
	fmt.Println()

	// Example 6: Load a reaction SMARTS
	fmt.Println("6. Loading reaction SMARTS:")
	smarts := "[C:1](=[O:2])[OH:3].[C:4][OH:5]>>[C:1](=[O:2])[O:5][C:4].[OH2:3]"
	fmt.Printf("   Input: %s\n", smarts)

	r2, err := reaction.LoadReactionSmartsFromString(smarts)
	if err != nil {
		log.Fatalf("Failed to load reaction SMARTS: %v", err)
	}
	defer r2.Close()

	r2ReactantCount, _ := r2.CountReactants()
	r2ProductCount, _ := r2.CountProducts()
	fmt.Printf("   Reactants: %d\n", r2ReactantCount)
	fmt.Printf("   Products: %d\n\n", r2ProductCount)

	// Example 7: Clone a reaction
	fmt.Println("7. Cloning a reaction:")
	r3, err := r.Clone()
	if err != nil {
		log.Fatalf("Failed to clone reaction: %v", err)
	}
	defer r3.Close()

	clonedReactants, _ := r3.CountReactants()
	clonedProducts, _ := r3.CountProducts()
	fmt.Printf("   Cloned reaction has %d reactants and %d products\n\n", clonedReactants, clonedProducts)

	// Example 8: Create a new empty reaction
	fmt.Println("8. Creating a new empty reaction:")
	r4, err := reaction.CreateReaction()
	if err != nil {
		log.Fatalf("Failed to create reaction: %v", err)
	}
	defer r4.Close()
	fmt.Println("   Empty reaction created successfully\n")

	fmt.Println("=== All examples completed successfully! ===")
}
