package main

import (
	"fmt"
	"log"

	"github.com/cx-luo/go-chem/molecule"
)

func main() {
	// Create a molecule from SMILES
	smiles := `<?xml version="1.0" encoding="UTF-8"?><cml xmlns="http://www.chemaxon.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.chemaxon.com/marvin/schema/mrvSchema_16_02_15.xsd" version="ChemAxon file format v16.02.15, generated by v17.28.0">
<MDocument><MChemicalStruct><molecule molID="m1"><atomArray atomID="a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18 a19 a20 a21 a22 a23 a24 a25 a26 a27 a28 a29" elementType="O C O C F F F O C N C C C C O N C O C O C C C C C N C C C" lonePair="2 0 2 0 3 3 3 2 0 1 0 0 0 0 2 1 0 2 0 2 0 0 0 0 0 1 0 0 0"></atomArray><bondArray><bond id="b1" atomRefs2="a1 a2" order="1"></bond><bond id="b2" atomRefs2="a2 a3" order="2"></bond><bond id="b3" atomRefs2="a2 a4" order="1"></bond><bond id="b4" atomRefs2="a4 a5" order="1"></bond><bond id="b5" atomRefs2="a4 a6" order="1"></bond><bond id="b6" atomRefs2="a4 a7" order="1"></bond><bond id="b7" atomRefs2="a8 a9" order="2"></bond><bond id="b8" atomRefs2="a9 a10" order="1"></bond><bond id="b9" atomRefs2="a10 a11" order="1"></bond><bond id="b10" atomRefs2="a11 a12" order="1"></bond><bond id="b11" atomRefs2="a12 a13" order="1"></bond><bond id="b12" atomRefs2="a13 a14" order="1"></bond><bond id="b13" atomRefs2="a14 a15" order="2"></bond><bond id="b14" atomRefs2="a14 a16" order="1"></bond><bond id="b15" atomRefs2="a16 a17" order="1"></bond><bond id="b16" atomRefs2="a11 a17" order="1"></bond><bond id="b17" atomRefs2="a17 a18" order="2"></bond><bond id="b18" atomRefs2="a10 a19" order="1"></bond><bond id="b19" atomRefs2="a19 a20" order="2"></bond><bond id="b20" atomRefs2="a19 a21" order="1"></bond><bond id="b21" atomRefs2="a21 a22" order="2"><bondStereo>T</bondStereo></bond><bond id="b22" atomRefs2="a22 a23" order="1"></bond><bond id="b23" atomRefs2="a23 a24" order="2"><bondStereo>T</bondStereo></bond><bond id="b24" atomRefs2="a24 a25" order="1"></bond><bond id="b25" atomRefs2="a25 a26" order="1"></bond><bond id="b26" atomRefs2="a26 a27" order="1"></bond><bond id="b27" atomRefs2="a23 a27" order="1"></bond><bond id="b28" atomRefs2="a24 a28" order="1"></bond><bond id="b29" atomRefs2="a28 a29" order="2"><bondStereo>T</bondStereo></bond><bond id="b30" atomRefs2="a9 a29" order="1"></bond><bond id="b31" atomRefs2="a21 a29" order="1"></bond></bondArray></molecule></MChemicalStruct></MDocument>
</cml>` // Aspirin
	mol, err := molecule.LoadMoleculeFromString(smiles)
	if err != nil {
		log.Fatalf("Failed to load molecule: %v", err)
	}
	defer mol.Close()

	fmt.Println("=== Molecule Format Conversion Examples ===\n")

	molecularFormula, err := mol.MolecularFormula()
	if err != nil {
		log.Fatalf("Failed to get molecular formula: %v", err)
	}
	fmt.Printf("Molecular formula: %s\n", molecularFormula)

	// 1. Basic SMILES
	if result, err := mol.ToSmiles(); err == nil {
		fmt.Printf("SMILES: %s\n", result)
	} else {
		fmt.Printf("SMILES Error: %v\n", err)
	}

	// 2. Canonical SMILES
	if result, err := mol.ToCanonicalSmiles(); err == nil {
		fmt.Printf("Canonical SMILES: %s\n", result)
	} else {
		fmt.Printf("Canonical SMILES Error: %v\n", err)
	}

	// 3. ChemAxon Extended SMILES (CXSmiles)
	fmt.Println("\n--- ChemAxon CXSmiles ---")
	if result, err := mol.ToCXSmiles(); err == nil {
		fmt.Printf("CXSmiles: %s\n", result)
	} else {
		fmt.Printf("CXSmiles Error: %v\n", err)
	}

	// 4. Canonical ChemAxon Extended SMILES
	if result, err := mol.ToCanonicalCXSmiles(); err == nil {
		fmt.Printf("Canonical CXSmiles: %s\n", result)
	} else {
		fmt.Printf("Canonical CXSmiles Error: %v\n", err)
	}

	// 5. SMARTS
	if result, err := mol.ToSmarts(); err == nil {
		fmt.Printf("\nSMARTS: %s\n", result)
	} else {
		fmt.Printf("SMARTS Error: %v\n", err)
	}

	// 6. CML (Chemical Markup Language)
	fmt.Println("\n--- CML Format ---")
	if result, err := mol.ToCML(); err == nil {
		fmt.Printf("CML: %s\n", result)
	} else {
		fmt.Printf("CML Error: %v\n", err)
	}

	// 7. CDXML
	fmt.Println("\n--- CDXML Format ---")
	if result, err := mol.ToCDXML(); err == nil {
		fmt.Printf("CDXML (first 200 chars): %s...\n", truncate(result, 200))
	} else {
		fmt.Printf("CDXML Error: %v\n", err)
	}

	// 8. CDX Base64
	fmt.Println("\n--- CDX Base64 Format ---")
	if result, err := mol.ToCDXBase64(); err == nil {
		fmt.Printf("CDX Base64 (first 100 chars): %s...\n", truncate(result, 100))
	} else {
		fmt.Printf("CDX Base64 Error: %v\n", err)
	}

	// 9. JSON (Ketcher format)
	fmt.Println("\n--- JSON/KET Format ---")
	if result, err := mol.ToJSON(); err == nil {
		fmt.Printf("JSON (first 200 chars): %s...\n", truncate(result, 200))
	} else {
		fmt.Printf("JSON Error: %v\n", err)
	}

	// 9a. KET format (alias for JSON)
	if result, err := mol.ToKet(); err == nil {
		fmt.Printf("KET (first 200 chars): %s...\n", truncate(result, 200))
	} else {
		fmt.Printf("KET Error: %v\n", err)
	}

	// 10. MOL file
	fmt.Println("\n--- MOL File Format ---")
	if result, err := mol.ToMolfile(); err == nil {
		fmt.Printf("MOL file (first 300 chars): %s...\n", truncate(result, 300))
	} else {
		fmt.Printf("MOL file Error: %v\n", err)
	}

	// 11. Save to various file formats
	fmt.Println("\n--- Saving to Files ---")

	// Save as MOL file
	if err := mol.SaveToFile("aspirin.mol"); err == nil {
		fmt.Println("✓ Saved to aspirin.mol")
	} else {
		fmt.Printf("✗ Failed to save MOL file: %v\n", err)
	}

	// Save as JSON/KET file
	if err := mol.SaveToJSONFile("aspirin.json"); err == nil {
		fmt.Println("✓ Saved to aspirin.json")
	} else {
		fmt.Printf("✗ Failed to save JSON file: %v\n", err)
	}

	// Save as KET file (Ketcher format)
	if err := mol.SaveToKetFile("aspirin.ket"); err == nil {
		fmt.Println("✓ Saved to aspirin.ket")
	} else {
		fmt.Printf("✗ Failed to save KET file: %v\n", err)
	}

	// 12. SDF Format (for multiple structures)
	fmt.Println("\n--- SDF Format ---")
	if result, err := mol.ToSDF(); err == nil {
		fmt.Printf("SDF (first 300 chars): %s...\n", truncate(result, 300))
	} else {
		fmt.Printf("SDF Error: %v\n", err)
	}

	// Save as SDF file
	if err := mol.SaveToSDF("aspirin.sdf"); err == nil {
		fmt.Println("✓ Saved to aspirin.sdf")
	} else {
		fmt.Printf("✗ Failed to save SDF file: %v\n", err)
	}

	fmt.Println("\n=== Format Conversion Complete ===")
}

// Helper function to truncate strings for display
func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen]
}
